Feat/verify endpoint
indie-devs/book-exchange-auth-service pull request #13
Opened 2022-08-02 09:07 UTC by hiiamtrong

2022-08-03 01:56 UTC, gialynguyen requested changes

2022-08-03 01:56 UTC, gialynguyen commented on src/utils/time/time.ts
> +  static isExpired(exp: number): boolean {
Should use a meaningful name like `expireTimestamp`.

2022-08-03 01:56 UTC, gialynguyen commented on src/auth/jwt.strategy.ts
> +    return user;
Should have a DTO for the `user` response of this method.

2022-08-03 01:56 UTC, gialynguyen commented on src/auth/auth.controller.ts
> +    res.set('x-user-id', req.user.id);
add these header field names to the configuration.

2022-08-03 02:07 UTC, gialynguyen requested changes

2022-08-03 02:07 UTC, gialynguyen commented on prisma/schema.prisma
>  }
I think the admin is a special role in our app and the permission mechanism isn't complex. So, we could add an `isAdmin` column.

2022-08-03 02:26 UTC, hiiamtrong commented on src/auth/jwt.strategy.ts
> +    return user;
Is that what you mean?
![image](https://user-images.githubusercontent.com/54925853/182510592-249e60d9-ebe4-4a53-bb7c-9d79e3e712a5.png)
So, is there any way to reuse the model UserAuth of PrismaClient

2022-08-03 15:12 UTC, gialynguyen commented on src/auth/jwt.strategy.ts
> +    return user;
Yes. I think we shouldn't reuse this time to reduce the cross dependency

2022-08-04 02:30 UTC, hiiamtrong commented on src/auth/jwt.strategy.ts
> +    return user;
Updated

2022-08-04 02:30 UTC, hiiamtrong commented on src/auth/auth.controller.ts
> +    res.set('x-user-id', req.user.id);
fixed

2022-08-04 02:30 UTC, hiiamtrong commented on prisma/schema.prisma
>  }
updated

2022-08-04 02:31 UTC, hiiamtrong commented on src/utils/time/time.ts
> +  static isExpired(exp: number): boolean {
fixed

2022-08-05 02:37 UTC, gialynguyen approved these changes

2022-08-05 02:37 UTC, merged